// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"createdAt"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"accountId"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Session struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	UserAgent    string       `json:"userAgent"`
	ClientIp     string       `json:"clientIp"`
	RefreshToken string       `json:"refreshToken"`
	IsBlocked    bool         `json:"isBlocked"`
	ExpiresAt    time.Time    `json:"expiresAt"`
	CreatedAt    sql.NullTime `json:"createdAt"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"fromAccountId"`
	ToAccountID   int64     `json:"toAccountId"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"createdAt"`
}

type User struct {
	ID                    int64     `json:"id"`
	Username              string    `json:"username"`
	HashedPassword        string    `json:"hashedPassword"`
	FullName              string    `json:"fullName"`
	Email                 string    `json:"email"`
	PhoneNumber           string    `json:"phoneNumber"`
	IsEmailVerified       bool      `json:"isEmailVerified"`
	IsPhoneNumberVerified bool      `json:"isPhoneNumberVerified"`
	PasswordChangedAt     time.Time `json:"passwordChangedAt"`
	CreatedAt             time.Time `json:"createdAt"`
}
