// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMoneyIntoAccount(ctx context.Context, arg AddMoneyIntoAccountParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, username string) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetEntry(ctx context.Context, accountID int64) (Entry, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByUsername(ctx context.Context, username string) (Session, error)
	GetTransfer(ctx context.Context, arg GetTransferParams) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListAccountsDesc(ctx context.Context, arg ListAccountsDescParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (Account, error)
	UpdateAccountByUsername(ctx context.Context, arg UpdateAccountByUsernameParams) (Account, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
	UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
