// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, username, user_agent, client_ip, refresh_token, is_blocked, expires_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, username, user_agent, client_ip, refresh_token, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	RefreshToken string    `json:"refreshToken"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.Username,
		arg.UserAgent,
		arg.ClientIp,
		arg.RefreshToken,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT 
id, username, user_agent, client_ip, refresh_token, is_blocked, expires_at, created_at FROM sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIdStmt, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByUsername = `-- name: GetSessionByUsername :one
SELECT 
id, username, user_agent, client_ip, refresh_token, is_blocked, expires_at, created_at FROM sessions WHERE username = $1 LIMIT 1
`

func (q *Queries) GetSessionByUsername(ctx context.Context, username string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByUsernameStmt, getSessionByUsername, username)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UserAgent,
		&i.ClientIp,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
