// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, balance, currency)
VALUES ($1, $2, $3)
RETURNING id, username, balance, currency, created_at
`

type CreateAccountParams struct {
	Username string `json:"username"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount, arg.Username, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE username = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.deleteAccountStmt, deleteAccount, username)
	return err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, username, balance, currency, created_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountById(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIdStmt, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByIdForUpdate = `-- name: GetAccountByIdForUpdate :one
SELECT id, username, balance, currency, created_at FROM accounts
WHERE id = $1 LIMIT 1 FOR NO KEY UPDATE
`

func (q *Queries) GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIdForUpdateStmt, getAccountByIdForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, balance, currency, created_at FROM accounts 
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByUsernameStmt, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, balance, currency, created_at FROM accounts
ORDER BY id LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.query(ctx, q.listAccountsStmt, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountById = `-- name: UpdateAccountById :one
UPDATE accounts
SET balance = $2
WHERE id = $1
RETURNING id, username, balance, currency, created_at
`

type UpdateAccountByIdParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountByIdStmt, updateAccountById, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountByUsername = `-- name: UpdateAccountByUsername :one
UPDATE accounts
SET balance = $2
WHERE username = $1
RETURNING id, username, balance, currency, created_at
`

type UpdateAccountByUsernameParams struct {
	Username string `json:"username"`
	Balance  int64  `json:"balance"`
}

func (q *Queries) UpdateAccountByUsername(ctx context.Context, arg UpdateAccountByUsernameParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountByUsernameStmt, updateAccountByUsername, arg.Username, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
