// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addMoneyIntoAccountStmt, err = db.PrepareContext(ctx, addMoneyIntoAccount); err != nil {
		return nil, fmt.Errorf("error preparing query AddMoneyIntoAccount: %w", err)
	}
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createEntryStmt, err = db.PrepareContext(ctx, createEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEntry: %w", err)
	}
	if q.createTransferStmt, err = db.PrepareContext(ctx, createTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransfer: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAccountStmt, err = db.PrepareContext(ctx, deleteAccount); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccount: %w", err)
	}
	if q.deleteEntryStmt, err = db.PrepareContext(ctx, deleteEntry); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEntry: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getAccountByIdStmt, err = db.PrepareContext(ctx, getAccountById); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountById: %w", err)
	}
	if q.getAccountByIdForUpdateStmt, err = db.PrepareContext(ctx, getAccountByIdForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByIdForUpdate: %w", err)
	}
	if q.getAccountByUsernameStmt, err = db.PrepareContext(ctx, getAccountByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByUsername: %w", err)
	}
	if q.getEntryStmt, err = db.PrepareContext(ctx, getEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntry: %w", err)
	}
	if q.getTransferStmt, err = db.PrepareContext(ctx, getTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransfer: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.listAccountsStmt, err = db.PrepareContext(ctx, listAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccounts: %w", err)
	}
	if q.listEntriesStmt, err = db.PrepareContext(ctx, listEntries); err != nil {
		return nil, fmt.Errorf("error preparing query ListEntries: %w", err)
	}
	if q.listTransfersStmt, err = db.PrepareContext(ctx, listTransfers); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransfers: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateAccountByIdStmt, err = db.PrepareContext(ctx, updateAccountById); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountById: %w", err)
	}
	if q.updateAccountByUsernameStmt, err = db.PrepareContext(ctx, updateAccountByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountByUsername: %w", err)
	}
	if q.updateEntryStmt, err = db.PrepareContext(ctx, updateEntry); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateEntry: %w", err)
	}
	if q.updateUserOTPStmt, err = db.PrepareContext(ctx, updateUserOTP); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserOTP: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addMoneyIntoAccountStmt != nil {
		if cerr := q.addMoneyIntoAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addMoneyIntoAccountStmt: %w", cerr)
		}
	}
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createEntryStmt != nil {
		if cerr := q.createEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEntryStmt: %w", cerr)
		}
	}
	if q.createTransferStmt != nil {
		if cerr := q.createTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAccountStmt != nil {
		if cerr := q.deleteAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccountStmt: %w", cerr)
		}
	}
	if q.deleteEntryStmt != nil {
		if cerr := q.deleteEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEntryStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getAccountByIdStmt != nil {
		if cerr := q.getAccountByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIdStmt: %w", cerr)
		}
	}
	if q.getAccountByIdForUpdateStmt != nil {
		if cerr := q.getAccountByIdForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIdForUpdateStmt: %w", cerr)
		}
	}
	if q.getAccountByUsernameStmt != nil {
		if cerr := q.getAccountByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByUsernameStmt: %w", cerr)
		}
	}
	if q.getEntryStmt != nil {
		if cerr := q.getEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntryStmt: %w", cerr)
		}
	}
	if q.getTransferStmt != nil {
		if cerr := q.getTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransferStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.listAccountsStmt != nil {
		if cerr := q.listAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccountsStmt: %w", cerr)
		}
	}
	if q.listEntriesStmt != nil {
		if cerr := q.listEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEntriesStmt: %w", cerr)
		}
	}
	if q.listTransfersStmt != nil {
		if cerr := q.listTransfersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransfersStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateAccountByIdStmt != nil {
		if cerr := q.updateAccountByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountByIdStmt: %w", cerr)
		}
	}
	if q.updateAccountByUsernameStmt != nil {
		if cerr := q.updateAccountByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountByUsernameStmt: %w", cerr)
		}
	}
	if q.updateEntryStmt != nil {
		if cerr := q.updateEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateEntryStmt: %w", cerr)
		}
	}
	if q.updateUserOTPStmt != nil {
		if cerr := q.updateUserOTPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserOTPStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	addMoneyIntoAccountStmt     *sql.Stmt
	createAccountStmt           *sql.Stmt
	createEntryStmt             *sql.Stmt
	createTransferStmt          *sql.Stmt
	createUserStmt              *sql.Stmt
	deleteAccountStmt           *sql.Stmt
	deleteEntryStmt             *sql.Stmt
	deleteUserStmt              *sql.Stmt
	getAccountByIdStmt          *sql.Stmt
	getAccountByIdForUpdateStmt *sql.Stmt
	getAccountByUsernameStmt    *sql.Stmt
	getEntryStmt                *sql.Stmt
	getTransferStmt             *sql.Stmt
	getUserStmt                 *sql.Stmt
	listAccountsStmt            *sql.Stmt
	listEntriesStmt             *sql.Stmt
	listTransfersStmt           *sql.Stmt
	listUsersStmt               *sql.Stmt
	updateAccountByIdStmt       *sql.Stmt
	updateAccountByUsernameStmt *sql.Stmt
	updateEntryStmt             *sql.Stmt
	updateUserOTPStmt           *sql.Stmt
	updateUserPasswordStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		addMoneyIntoAccountStmt:     q.addMoneyIntoAccountStmt,
		createAccountStmt:           q.createAccountStmt,
		createEntryStmt:             q.createEntryStmt,
		createTransferStmt:          q.createTransferStmt,
		createUserStmt:              q.createUserStmt,
		deleteAccountStmt:           q.deleteAccountStmt,
		deleteEntryStmt:             q.deleteEntryStmt,
		deleteUserStmt:              q.deleteUserStmt,
		getAccountByIdStmt:          q.getAccountByIdStmt,
		getAccountByIdForUpdateStmt: q.getAccountByIdForUpdateStmt,
		getAccountByUsernameStmt:    q.getAccountByUsernameStmt,
		getEntryStmt:                q.getEntryStmt,
		getTransferStmt:             q.getTransferStmt,
		getUserStmt:                 q.getUserStmt,
		listAccountsStmt:            q.listAccountsStmt,
		listEntriesStmt:             q.listEntriesStmt,
		listTransfersStmt:           q.listTransfersStmt,
		listUsersStmt:               q.listUsersStmt,
		updateAccountByIdStmt:       q.updateAccountByIdStmt,
		updateAccountByUsernameStmt: q.updateAccountByUsernameStmt,
		updateEntryStmt:             q.updateEntryStmt,
		updateUserOTPStmt:           q.updateUserOTPStmt,
		updateUserPasswordStmt:      q.updateUserPasswordStmt,
	}
}
