// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password, email, full_name, phone_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, hashed_password, full_name, email, phone_number, is_email_verified, is_phone_number_verified, password_changed_at, created_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashedPassword"`
	Email          string `json:"email"`
	FullName       string `json:"fullName"`
	PhoneNumber    string `json:"phoneNumber"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.FullName,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.IsPhoneNumberVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, username)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, full_name, email, phone_number, is_email_verified, is_phone_number_verified, password_changed_at, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.IsPhoneNumberVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, hashed_password, full_name, email, phone_number, is_email_verified, is_phone_number_verified, password_changed_at, created_at FROM users
ORDER BY id LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.IsEmailVerified,
			&i.IsPhoneNumberVerified,
			&i.PasswordChangedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserOTP = `-- name: UpdateUserOTP :one
UPDATE users
SET is_email_verified = $2, is_phone_number_verified = $3
WHERE username = $1
RETURNING id, username, hashed_password, full_name, email, phone_number, is_email_verified, is_phone_number_verified, password_changed_at, created_at
`

type UpdateUserOTPParams struct {
	Username              string `json:"username"`
	IsEmailVerified       bool   `json:"isEmailVerified"`
	IsPhoneNumberVerified bool   `json:"isPhoneNumberVerified"`
}

func (q *Queries) UpdateUserOTP(ctx context.Context, arg UpdateUserOTPParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserOTPStmt, updateUserOTP, arg.Username, arg.IsEmailVerified, arg.IsPhoneNumberVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.IsPhoneNumberVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET hashed_password = $2, password_changed_at = $3
WHERE username = $1
RETURNING id, username, hashed_password, full_name, email, phone_number, is_email_verified, is_phone_number_verified, password_changed_at, created_at
`

type UpdateUserPasswordParams struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashedPassword"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.Username, arg.HashedPassword, arg.PasswordChangedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.IsPhoneNumberVerified,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
