name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend-Team
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:18-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: project_test_kk
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5433:5432
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Install migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
    - name: Create the tables in postgres
      run: make migrateup
    - name: Test
      run: |
        go mod tidy
        make test